[[manager.prepend_keymap]]
on = ["i"]
run = "plugin keyjump --sync --args=keep"
desc = "Keyjump (Keep mode)"

[[manager.prepend_keymap]]
on = ["l"]
run = "plugin --sync smart-enter"
desc = "Enter the child directory, or open the file"

[[manager.prepend_keymap]]
on = ["C"]
run = "plugin ouch --args=zip"
desc = "Compress with ouch"

[input]
append_keymap = [
  { on = [
    "j",
    "j",
  ], run = "escape", desc = "Remap jj to ecape insert mode" },
]
