[[manager.prepend_keymap]]
on   = [ "i" ]
exec = "plugin keyjump --sync --args=keep"
desc = "Keyjump (Keep mode)"

[[manager.prepend_keymap]]
on   = [ "l" ]
exec = "plugin --sync smart-enter"
desc = "Enter the child directory, or open the file"

[input]
append_keymap = [
    { on = [ "j", "j" ], exec = "escape", desc = "Remap jj to ecape insert mode" },
]
